python Train_S3_Downsampling.py -i 0
python Train_S3_Downsampling.py -i 1
python Train_S3_Downsampling.py -i 2
python Train_S3_Downsampling.py -i 3
python Train_S3_Downsampling.py -i 4
python Train_S3_Downsampling.py -i 5
python Train_S3_Downsampling.py -i 6
python Train_S3_Downsampling.py -i 7
python Train_S3_Downsampling.py -i 8
python Train_S3_Downsampling.py -i 9